apiVersion: v2
name: towonel-operator
description: Kubernetes operator for Towonel tunnels and agents
type: application
version: 1.3.0
appVersion: "1.3.0"
kubeVersion: ">=1.31.0-0"
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 5.0.1
