//go:build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright the towonel-operator authors.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecord) DeepCopyInto(out *DNSRecord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecord.
func (in *DNSRecord) DeepCopy() *DNSRecord {
	if in == nil {
		return nil
	}
	out := new(DNSRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeRef) DeepCopyInto(out *EdgeRef) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeRef.
func (in *EdgeRef) DeepCopy() *EdgeRef {
	if in == nil {
		return nil
	}
	out := new(EdgeRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortAllocation) DeepCopyInto(out *PortAllocation) {
	*out = *in
	in.Edge.DeepCopyInto(&out.Edge)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortAllocation.
func (in *PortAllocation) DeepCopy() *PortAllocation {
	if in == nil {
		return nil
	}
	out := new(PortAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TowonelTunnel) DeepCopyInto(out *TowonelTunnel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TowonelTunnel.
func (in *TowonelTunnel) DeepCopy() *TowonelTunnel {
	if in == nil {
		return nil
	}
	out := new(TowonelTunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TowonelTunnel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TowonelTunnelList) DeepCopyInto(out *TowonelTunnelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TowonelTunnel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TowonelTunnelList.
func (in *TowonelTunnelList) DeepCopy() *TowonelTunnelList {
	if in == nil {
		return nil
	}
	out := new(TowonelTunnelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TowonelTunnelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TowonelTunnelSpec) DeepCopyInto(out *TowonelTunnelSpec) {
	*out = *in
	if in.FailoverRegions != nil {
		in, out := &in.FailoverRegions, &out.FailoverRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.ExtraHostnames != nil {
		in, out := &in.ExtraHostnames, &out.ExtraHostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.DNS = in.DNS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TowonelTunnelSpec.
func (in *TowonelTunnelSpec) DeepCopy() *TowonelTunnelSpec {
	if in == nil {
		return nil
	}
	out := new(TowonelTunnelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TowonelTunnelStatus) DeepCopyInto(out *TowonelTunnelStatus) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.AuthorizedHostnames != nil {
		in, out := &in.AuthorizedHostnames, &out.AuthorizedHostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PortAllocations != nil {
		in, out := &in.PortAllocations, &out.PortAllocations
		*out = make([]PortAllocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Edges != nil {
		in, out := &in.Edges, &out.Edges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DNSRecords != nil {
		in, out := &in.DNSRecords, &out.DNSRecords
		*out = make([]DNSRecord, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TowonelTunnelStatus.
func (in *TowonelTunnelStatus) DeepCopy() *TowonelTunnelStatus {
	if in == nil {
		return nil
	}
	out := new(TowonelTunnelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelDNSSpec) DeepCopyInto(out *TunnelDNSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelDNSSpec.
func (in *TunnelDNSSpec) DeepCopy() *TunnelDNSSpec {
	if in == nil {
		return nil
	}
	out := new(TunnelDNSSpec)
	in.DeepCopyInto(out)
	return out
}
